version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13-alpine
    restart: unless-stopped
    hostname: postgres
    ports:
      - 5433:5434
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data: